### ISSUE TITLE
Can you publish this to npm?

### ISSUE THREAD

**Issue by RobertMenke** [lookapanda/jquery-hashtags#7]
I know this cold is over a year old, but would you mind publishing this to NPM so we can manage it as a dependency with webpack/es6? Thanks!

**Comment by lookapanda** [comment]
Hi @RobertMenke 
I published it to npm:
https://www.npmjs.com/package/jquery-hashtags

I didn't test if it's usable in webpack/es6 though, feel free to do so but keep in mind that I cannot give support for that.

**Comment by cyorobert** [comment]
Thank you. You can shim modules with webpack so I think it will be fine - just have to make sure jQuery is global like the plugin expects it to be. I appreciate the quick response.
